### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/turing-test#50]
- [ ] - turc régler PB piston
- [ ] - jeton métal morpion
- [ ] - chargeur batterie
- [ ] - acheter 1 ou 2 2S
- [ ] - petits papiers
- [ ] - réparer raccord ms20
- [ ] - refaire soudure cassée sur la table
- [ ] - changer servo caro
- [ ] - mettre pince eteau dans liste matos
- [ ] - mettre pieds découpe dans liste matos
- [ ] - mettre découpes dans liste matos

**Comment by LeonLenclos** [comment]
- réparer raccord ms20

**Comment by LeonLenclos** [comment]
- refaire soudure cassée sur la table

**Comment by LeonLenclos** [comment]
- Mettre pince eteau dans liste matos
- mettre pieds découpe dans liste matos

**Comment by BertrandLenclos** [comment]
basculé dans les todo du site
